---
# Supported outputs: stdout, ledstrip
output: stdout

# GPIO pin connected to the pixels (18 uses PWM!).
led_pin: 18

# Number of LED pixels in a strip
led_count: 300

# Set to 0 for darkest and 255 for brightest
led_brightness: 128

scenes:
  - name: map
    interval: 1
    programs:
      - key: ranged_rainbow_cycle
        start: 0
        end: 100
      - key: ranged_rainbow_cycle
        start: 200
        end: 300
