---
# Supported outputs: stdout, ledstrip
output: ledstrip

# GPIO pin connected to the pixels (18 uses PWM!).
led_pin: 18

# Number of LED pixels in a strip
led_count: 960

# Set to 0 for darkest and 255 for brightest
led_brightness: 192

scenes:
  - name: static_color
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 960
        red: 255
        green: 0
        blue: 10
        wait_time: 3000
  - name: running_lights_strobe
    interval: 1
    programs:
      - key: running_lights
        start: 0
        end: 360
        iterations: 200
        wait_time: 50
        red: 255
        green: 0
        blue: 10
      - key: strobe
        start: 360
        end: 960
        iterations: 40
        wait_time: 500
        red: 255
        green: 0
        blue: 10
  - name: static_running_lights
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 255
        green: 0
        blue: 10
        wait_time: 3000
      - key: running_lights
        start: 360
        end: 960
        iterations: 200
        wait_time: 1
        red: 255
        green: 0
        blue: 10
  - name: static_outside_to_center
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 255
        green: 0
        blue: 10
        wait_time: 3000
      - key: outside_to_center
        start: 360
        end: 960
        size: 128
        red: 255
        green: 0
        blue: 10
        speed: 1
        wait_time: 100
  - name: center
    interval: 1
    programs:
      - key: center_to_outside
        start: 0
        end: 360
        size: 120
        red: 255
        green: 0
        blue: 10
        speed: 1
        wait_time: 1
      - key: static_color
        start: 360
        end: 960
        red: 255
        green: 0
        blue: 10
        wait_time: 3000
  - name: twinkle
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 255
        green: 0
        blue: 10
        wait_time: 3000
      - key: twinkle
        start: 360
        end: 960
        red: 255
        green: 0
        blue: 10
        one_led_per_scene: false
        wait_time: 1
        iterations: 300
  - name: strobe
    interval: 1
    programs:
      - key: strobe
        start: 0
        end: 960
        iterations: 30
        wait_time: 500
        red: 255
        green: 0
        blue: 10
  - name: color_chasers
    interval: 1
    programs:
      - key: color_chase
        start: 0
        end: 180
        red: 255
        green: 0
        blue: 10
        wait_time: 10
      - key: color_chase_reverse
        start: 180
        end: 360
        red: 255
        green: 0
        blue: 10
        wait_time: 10
      - key: static_color
        start: 360
        end: 960
        red: 255
        green: 0
        blue: 10
        wait_time: 3000
  - name: running_lights
    interval: 1
    programs:
      - key: strobe
        start: 0
        end: 360
        iterations: 40
        wait_time: 500
        red: 255
        green: 0
        blue: 10
      - key: running_lights
        start: 360
        end: 960
        iterations: 200
        wait_time: 50
        red: 255
        green: 0
        blue: 10
  - name: static_meteor_rain
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 255
        green: 0
        blue: 10
        wait_time: 3000
      - key: meteor_rain
        start: 360
        end: 960
        red: 255
        green: 0
        blue: 10
        size: 32
        random_decay: true
        trail_decay: 64
        wait_time: 1
  - name: directional
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 255
        green: 0
        blue: 10
        wait_time: 3000
      - key: snow_sparkle
        start: 360
        end: 960
        red: 255
        green: 0
        blue: 10
        one_led_per_scene: false
        wait_time: 10
        iterations: 50
  - name: snow_sparkle
    interval: 200
    programs:
      - key: snow_sparkle
        start: 0
        end: 960
        red: 255
        green: 0
        blue: 10
        one_led_per_scene: false
        wait_time: 10
        iterations: 50
  - name: snow_sparkle_with_static
    interval: 10
    programs:
      - key: snow_sparkle
        start: 0
        end: 360
        red: 255
        green: 0
        blue: 10
        wait_time: 1
      - key: static_color
        start: 360
        end: 960
        red: 255
        green: 0
        blue: 10
        wait_time: 3000
  - name: static_color
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 255
        green: 0
        blue: 10
        wait_time: 3000
      - key: static_rainbow
        start: 360
        end: 960
        wait_time: 3000
  - name: chaos_colors
    interval: 1
    programs:
      - key: chaos_colors
        wait_time: 3000
        speed: 50
        start: 0
        end: 360
      - key: chaos_fill_down
        wait_time: 3000
        speed: 1
        start: 360
        end: 960
  - name: static_color
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 960
        red: 10
        green: 0
        blue: 255
        wait_time: 3000
  - name: running_lights_strobe
    interval: 1
    programs:
      - key: running_lights
        start: 0
        end: 360
        iterations: 200
        wait_time: 50
        red: 10
        green: 0
        blue: 255
      - key: strobe
        start: 360
        end: 960
        iterations: 40
        wait_time: 500
        red: 10
        green: 0
        blue: 255
  - name: static_running_lights
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 10
        green: 0
        blue: 255
        wait_time: 3000
      - key: running_lights
        start: 360
        end: 960
        iterations: 200
        wait_time: 1
        red: 10
        green: 0
        blue: 255
  - name: static_outside_to_center
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 10
        green: 0
        blue: 255
        wait_time: 3000
      - key: outside_to_center
        start: 360
        end: 960
        size: 128
        red: 10
        green: 0
        blue: 255
        speed: 1
        wait_time: 100
  - name: center
    interval: 1
    programs:
      - key: center_to_outside
        start: 0
        end: 360
        size: 120
        red: 10
        green: 0
        blue: 255
        speed: 1
        wait_time: 1
      - key: static_color
        start: 360
        end: 960
        red: 10
        green: 0
        blue: 255
        wait_time: 3000
  - name: twinkle
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 10
        green: 0
        blue: 255
        wait_time: 3000
      - key: twinkle
        start: 360
        end: 960
        red: 10
        green: 0
        blue: 255
        one_led_per_scene: false
        wait_time: 1
        iterations: 300
  - name: strobe
    interval: 1
    programs:
      - key: strobe
        start: 0
        end: 960
        iterations: 20
        wait_time: 500
        red: 10
        green: 0
        blue: 255
  - name: color_chasers
    interval: 1
    programs:
      - key: color_chase
        start: 0
        end: 180
        red: 10
        green: 0
        blue: 255
        wait_time: 10
      - key: color_chase_reverse
        start: 180
        end: 360
        red: 10
        green: 0
        blue: 255
        wait_time: 10
      - key: static_color
        start: 360
        end: 960
        red: 10
        green: 0
        blue: 255
        wait_time: 3000
  - name: running_lights
    interval: 1
    programs:
      - key: strobe
        start: 0
        end: 360
        iterations: 40
        wait_time: 500
        red: 10
        green: 0
        blue: 255
      - key: running_lights
        start: 360
        end: 960
        iterations: 200
        wait_time: 50
        red: 10
        green: 0
        blue: 255
  - name: static_meteor_rain
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 10
        green: 0
        blue: 255
        wait_time: 3000
      - key: meteor_rain
        start: 360
        end: 960
        red: 10
        green: 0
        blue: 255
        size: 32
        random_decay: true
        trail_decay: 64
        wait_time: 1
  - name: directional
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 10
        green: 0
        blue: 255
        wait_time: 3000
      - key: snow_sparkle
        start: 360
        end: 960
        red: 10
        green: 0
        blue: 255
        one_led_per_scene: false
        wait_time: 10
        iterations: 50
  - name: snow_sparkle
    interval: 200
    programs:
      - key: snow_sparkle
        start: 0
        end: 960
        red: 10
        green: 0
        blue: 255
        one_led_per_scene: false
        wait_time: 10
        iterations: 50
  - name: snow_sparkle_with_static
    interval: 10
    programs:
      - key: snow_sparkle
        start: 0
        end: 360
        red: 10
        green: 0
        blue: 255
        wait_time: 1
      - key: static_color
        start: 360
        end: 960
        red: 10
        green: 0
        blue: 255
        wait_time: 3000
  - name: static_color
    interval: 1
    programs:
      - key: static_color
        start: 0
        end: 360
        red: 10
        green: 0
        blue: 255
        wait_time: 3000
      - key: static_rainbow
        start: 360
        end: 960
        wait_time: 3000
  - name: chaos_colors
    interval: 1
    programs:
      - key: chaos_colors
        wait_time: 3000
        speed: 50
        start: 0
        end: 360
      - key: chaos_fill_down
        wait_time: 3000
        speed: 1
        start: 360
        end: 960
