---
# Supported outputs: stdout, ledstrip
output: stdout

# GPIO pin connected to the pixels (18 uses PWM!).
led_pin: 18

# Number of LED pixels in a strip
led_count: 300

# Set to 0 for darkest and 255 for brightest
led_brightness: 128

scenes:
  - name: test
    interval: 1
    programs:
      - key: ranged_rainbow_cycle
        start: 0
        end: 100
      - key: ranged_rainbow_cycle
        start: 200
        end: 300
  - name: map
    interval: 1
    programs:
      - key: mapper
        map:
          - min: 1
            max: 25
          - min: 25
            max: 50
          - min: 50
            max: 150
          - min: 150
            max: 250
          - min: 250
            max: 275
          - min: 275
            max: 300
